INFO: Starting training:
        Epochs:          5
        Batch size:      1
        Learning rate:   1e-05
        Training size:   759
        Validation size: 84
        Checkpoints:     True
        Device:          cpu
        Images scaling:  0.5
        Mixed Precision: False
Epoch 1/5:   0%|                                                                                                    | 0/759 [00:00<?, ?img/s]D:\Python37\lib\site-packages\torch\autocast_mode.py:162: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
Epoch 1/5:   0%|                                                                                                    | 0/759 [00:05<?, ?img/s]
Traceback (most recent call last):
  File "train.py", line 191, in <module>
    amp=args.amp)
  File "train.py", line 93, in train_net
    loss = criterion(masks_pred, true_masks) \
  File "D:\Python37\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Python37\lib\site-packages\torch\nn\modules\loss.py", line 1165, in forward
    label_smoothing=self.label_smoothing)
  File "D:\Python37\lib\site-packages\torch\nn\functional.py", line 2996, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
IndexError: Target 255 is out of bounds.